[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.blade.php,*.tsx,*.jsx'
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
" Vim を開く際にディレクトリを指定した場合に自動的にツリーを開く
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
" 最後に残されたウィンドウがツリーのみの場合に Vim を終了する
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = ['~/.vim/templates']
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
let g:cheatsheet#cheat_file = '~/.vim/templates/vimCheatSheet.md'
let g:cheatsheet#float_window = 1
let g:cheatsheet#float_window_width_ratio = 0.6
let g:cheatsheet#float_window_height_ratio = 0.6
'''

[[plugins]]
repo = 'glacambre/firenvim'
hook_add = '''
set guifont=Consolas:h18
'''
hook_post_update = '''
call firenvim#install(0)
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

